site_name: Guidebolt Knowledge Base

site_url: https://k.guidebolt.com

site_description: An efficient technical knowledge base

site_author: Guidebolt Inc.

copyright: Creative Commons Zero 1.0

repo_url: https://github.com/guidebolt/knowledge

nav:
    -  'README.md'
    -  'intro.md'
    -  'critical-thinking.md'
    -  'tools.md'
    -  'system.md'
    -  'mech.md'
    -  'elec.md'
    -  'software.md'
    -  'business.md'
    -  'cnc-machining.md'
    -  'changelog.md'

theme:
    name: material
    custom_dir: overrides
    palette:
        scheme: default
        primary: custom
    logo: assets/logo.png
    favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.expand
        - navigation.sections

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.magiclink

extra_css:
  - assets/extra.css
  
extra:
  analytics:
    provider: custom
    property: foobar 

