site_name: Guidebolt Knowledge Base

site_url: https://knowledge.guidebolt.com

site_description: An efficient knowledge base with technical focus

site_author: Guidebolt

copyright: Creative Commons Zero

repo_url: https://github.com/guidebolt/knowledge

theme:
    name: material


