site_name: Guidebolt Knowledge Base

site_url: https://k.guidebolt.com

site_description: An efficient technical knowledge base

site_author: Guidebolt Inc.

copyright: Unlicense

repo_url: https://github.com/guidebolt/knowledge

theme:
    name: material
    features:
        - navigation.instant
        - navigation.expand
        - navigation.sections

markdown_extensions:
  - admonition
